version: "3"

services:
  n8n:
    build: .
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      # - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - WEBHOOK_URL=https://${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - NODE_FUNCTION_ALLOW_BUILTIN=*
    volumes:
      - ${DATA_FOLDER}/.n8n:/home/node/.n8n
      - ./files:/files
